plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services' // Google services plugin for Firebase
}

android {
    namespace 'com.shivayscreation'
    compileSdk 35

    defaultConfig {
        applicationId "com.shivayscreation"
        minSdk 26
        targetSdk 34 // Updated target SDK version
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        lintOptions {
            checkReleaseBuilds false
            baseline file("lint-baseline.xml")
        }
    }

    buildTypes {
        release {
            minifyEnabled false // Set to true for Proguard obfuscation if required
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    // Java Toolchain (ensure compatibility with Java 17)
    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }
}

dependencies {
    // AndroidX and Material Libraries
    implementation 'androidx.annotation:annotation:1.9.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'

    // For responsive design/UI
    implementation 'com.intuit.sdp:sdp-android:1.1.0'

    // Firebase BoM (Bill of Materials)
    implementation platform('com.google.firebase:firebase-bom:33.10.0')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-database'
    implementation 'com.google.firebase:firebase-storage:21.0.1'
    implementation("commons-beanutils:commons-beanutils:1.9.4") // Updated version
    implementation("commons-collections:commons-collections:3.2.2") // add this line


    // Image Loading and Circular Image Views
    implementation 'de.hdodenhof:circleimageview:3.1.0'

    // Razorpay Payment Gateway Integration
    implementation 'com.razorpay:checkout:1.6.41'

    // Groovy HTTP Builder (For HTTP requests if needed)
    implementation 'org.codehaus.groovy.modules.http-builder:http-builder:0.7.1'

    // Testing Libraries
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}


apply plugin: 'com.google.gms.google-services' // Apply Google services for Firebase

